### ISSUE TITLE
future of arc_unpacker

### ISSUE THREAD

**Issue by 0xh3LL0** [vn-tools/arc_unpacker#100]
microsoft replace cmd with powershell in latest version of windows, and probably will completely remove it...
http://news.softpedia.com/news/microsoft-replaces-command-prompt-with-powershell-in-latest-windows-10-build-510328.shtml

what should we (user of arc_unpacker and your self) do?
should we stick with current/earlier version of windows? or make a GUI, probably?

**Comment by mrsshr** [comment]
powershell can execute any CLI programs with arguments.

**Comment by rr-** [comment]
What @mrsshr says.

Think of Powershell as of "better cmd".
