### ISSUE TITLE
can't find any unpacked stuff in root

### ISSUE THREAD

**Issue by yourworsthero** [vn-tools/arc_unpacker#110]
## Game info

Fate/Stay night

## Details

unpacking bgimg and fgimg.xp3 in fsn in cmd, i unpacked successfully and it said
"Saving to c:/program files (x86)/Fate/bgimage.xp3~/xxxxx.png.... ok" but i couldn't find any folder or png files on my fate folder.

I tried again with another xp3 file but it still unpacked successfully but there aren't files nor folder.

**Comment by rr-** [comment]
Maybe you don't have permissions to create files in program files? What happens if you run it somewhere else?

**Comment by rr-** [comment]
Closing due to lack of info
