### ISSUE TITLE
is there any packer/re-packer for it?

### ISSUE THREAD

**Issue by aqualaguna** [vn-tools/arc_unpacker#115]
## Details
i need to pack it to save my change for it how is it done?

For bug reports, put information what went wrong here.

**Comment by Neroldy** [comment]
@aqualaguna Like the name, maybe you need to write the packer code by yourself...
Sometimes the game will first try to read the unpacked file, if not found, then will read the package.
You can direct put the file in your folder. Anyway, you will need OD to understand your game engine.
