### ISSUE TITLE
solved, ty bye

### ISSUE THREAD

**Issue by EredarStormrage** [vn-tools/arc_unpacker#116]
## Game info

VNDB link: [Atelier Kaguya][100226]AneDeath. ~Anejini Kakugo no Otouto Shibori na Natsu ga Kuru!~
Developer: 
Release date: 20/2/2017
Original title: fix this
English title (if available): what is this?

## Details
![image](https://cloud.githubusercontent.com/assets/25906550/23136506/e5d1751a-f751-11e6-81cb-b9713de51417.png)

you see what is wrong here, don't need to talk much

**Comment by hktkqj** [comment]
I wonder how you fixed this problem, cuz I got the same "Missing decryption params" error log here :(

**Comment by Ashcoop** [comment]
> I wonder how you fixed this problem, cuz I got the same "Missing decryption params" error log here :(

Make sure the ARC file you use is the onefrom default installation folder, and not the one that you copied elsewhere.

![Untitled](https://user-images.githubusercontent.com/62887690/77914361-fdc3a980-72bf-11ea-8f71-6a364f3d2594.png)
![Untitled2](https://user-images.githubusercontent.com/62887690/77914367-fef4d680-72bf-11ea-8d65-1c39aacd0ba8.png)

For example, the ARC file that's in "D:\ARC Unpacker\cg00.arc" is the one I copied from the default installation folder, therefore it doesn't work (red error text).
On the other hand, the ARC file that's in "G:\Data\cg00.arc" is the one from the default installation folder, therefore it works (green text).
Also, make sure to use [--out="DIRECTORY HERE"] at the end to set the output folder. 

You can use the first picture as reference.
