### ISSUE TITLE
When you will start Work on games ?

### ISSUE THREAD

**Issue by marconii2002** [vn-tools/arc_unpacker#117]
When you will start work on games ?

**Comment by rr-** [comment]
I won't be actively working on this project until further notice. This is open source project, feel free to contribute.

**Comment by marconii2002** [comment]
Then can you show me how to create cyberworks plugin. 
How to find this values 
 {0xE9, 0xEF, 0xFB},
            {4, 5, _, _, _, _, 6, _, _, 3, _, _, _, 0, _, _, _, 7, _, _},
false,
