### ISSUE TITLE
Add Tomoyo After to the supported game list

### ISSUE THREAD

**Issue by jyrkive** [vn-tools/arc_unpacker#137]
## Game info

VNDB link: https://vndb.org/v12
Developer: Key
Release date: 2005-11-25
Original title: 智代アフター ～It’s a Wonderful Life～
English title (if available): Tomoyo After \~It's a Wonderful Life\~

## Details

The game list page says "If a game isn't listed below and it works, please let me know so I can update the table." And I can confirm that I can extract graphics and music from Tomoyo After (English Edition, 2016-07-01) with arc_unpacker. 👍 

Needs `--dec=real-live/g00` for graphics and `--dec=real-live/nwa` for music.

**Comment by rr-** [comment]
Thanks
