### ISSUE TITLE
Build on Visual C++

### ISSUE THREAD

**Issue by acaly** [vn-tools/arc_unpacker#18]
Hi,

First thanks for your work. I have been looking for a tool like this for long.

I try to build it on Visual C++. At least it successfully builds and it seems working on Touhou 13. ```test``` not tried yet.

I have made two modifications. 

1. In ```formats/archives.cc``` function ```void Archive::unpack(File &file, FileSaver &file_saver)```, the lambda expression captures ```file_saver_proxy``` which is not initialized. VC++ (I'm using Visual Studio 2013 v120) does not support that. By creating a ```p_file_saver_proxy``` and capture that by reference, and after setting ```p_file_saver_proxy```, pointing ```p_file_saver_proxy``` to ```p_file_saver_proxy```, it can be successfully built. (I'm not sure whether this modification is legal, according to the logic of your program.)

2. In ```formats/kirikiri/tlg_converter.cc```, ```std::unique_ptr<File> decode_tlg_0(File &file)```, change ```::decode``` to ```decode```. (In VC++, functions in inline namespace can not be refered to as this.)

Another issue is that usually the ```aux``` folder can not be created on Windows. Would you mind giving it another name?

Though it is working, I don't think it's easy to have fully support for VC++ (or some other build tools supporting VC++ like CMake). But if you like, I can have a try.

**Comment by rr-** [comment]
Whoa, that's quite a few issues at once! I'm going to fix the AUX folder in a few hours.
Could you please create a pull request that shows the changes regarding `p_file_saver_proxy` so I can verify your fix?

Regarding general support for VS: like I said in README, pull requests are totally welcome, but I can't support it myself as I don't have neither VS or Windows. As long as it doesn't pollute `/` which should contain as few files as possible, I'm totally okay with it.

**Comment by acaly** [comment]
I missed one modification... Edited. So there are two.

I will create a pull request after aux is fixed, which prevents git clone.

**Comment by rr-** [comment]
Actually, for some reason I could clone it on this machine even though it's Windows as well.
The `aux` folder has been renamed to `extra`.

**Comment by rr-** [comment]
>In formats/kirikiri/tlg_converter.cc, std::unique_ptr<File> decode_tlg_0(File &file), change ::decode to decode. (In VC++, functions in inline namespace can not be refered to as this.)

In gcc and mingw, firing `decode` rather than `::decode` at line 132 will cause infinite recursion. I'm going to rename it to something different.

**Comment by rr-** [comment]
Please let me know if changing `archive.cc` like this:

    diff --git a/src/formats/archive.cc b/src/formats/archive.cc
    index 9d1d9f3..d8fd8f8 100644
    --- a/src/formats/archive.cc
    +++ b/src/formats/archive.cc
    @@ -5,8 +5,10 @@ void Archive::unpack(File &file, FileSaver &file_saver) const
         if (!is_recognized(file))
             throw std::runtime_error("File is not recognized");
    
    +    FileSaverCallback file_saver_proxy;
    +
         //every file should be passed through registered transformers
    -    FileSaverCallback file_saver_proxy([&](std::shared_ptr<File> saved_file)
    +    file_saver_proxy.set_callback([&](std::shared_ptr<File> saved_file)
         {
             for (auto &transformer : transformers)
             {

lets you compile it in VS.

**Comment by acaly** [comment]
Thanks!

And sorry, I just find there are two more. As I did not use git, it turned out to be difficult to point out modifications.

In ```formats/microsoft/dds_converter.cc```, there is a function called max, while on Windows, WindowsAPI provide a macro named ```max```, prevent the function declaration from compiling. I'm not sure how this header is included. But as this function is never used, how about just removing it.

In ```formats/microsoft/exe_archive.cc```, the character in ```path_sep``` is not recognized. Maybe using ```\x``` will fix.

And as for ```file_saver_proxy```, ```set_callback``` works fine.

Anyway, I can check them on the new branch. Please wait for my result.

**Comment by acaly** [comment]
After some efforts CMake is working now. Please check the changes in [my fork](https://github.com/acaly/arc_unpacker) and let me know your suggestions. And I want to know whether CMake also works for linux.

On VS, there is still an error produced by the linker (caused by the auto-linking lib file in Boost). But it can be easily fixed by manually adding a library directory. My CMake can not properly do it. I will update the README and create a pull request later.

**Comment by rr-** [comment]
You should fire a pull request so I can verify the changes here. (You will be able to correct things by committing to your repository.)

**Comment by rr-** [comment]
N.b. have you tried to adapt the existing build system, [http://docs.waf.googlecode.com/git-history/b0f9489b1c5b4d58a23e139bfbb51db82f650823/apidocs_16/tools/msvc.html](waf), to use MSVC? Apparently it's supported.

**Comment by rr-** [comment]
Closed in https://github.com/vn-tools/arc_unpacker/commit/7dde78b15142cb2cb1db17a3ba3a78098bbf8425 .
