### ISSUE TITLE
Help, please add support files .cpz - Purple Software(パープルソフトウェア)

### ISSUE THREAD

**Issue by EAxp3** [vn-tools/arc_unpacker#22]
Please support archive .cpz
extract archives cg :(

archive .cpz
images .pb3

CMVS

Extract Games
-Hapymaher
-Hapymaher -Fragmentation Dream
-Chrono Clock

Info Game:

https://vndb.org/p132
http://www.purplesoftware.jp/main.php

I need help please
there is no extract tool cg

Thank you
I'll be waiting... :)

let me know if you need the game files

Thank you

Please

more information tools:
http://blog.sina.com.cn/s/blog_5e29812f0100r8ku.html

more information:
game files+others
link: https://mega.nz/#!AkoxCKKR!AuOucLZbt7adRUqI0Fc8upxEssPpIa64vnay82TfQiE

Please Support.....Thank you ;)

cmvs32.exeを
00051350 75 18 → EB 59

**Comment by rr-** [comment]
I'm on it~
Please give me a few days - the format looks somewhat complex.

**Comment by rr-** [comment]
Added support for CPZ5 archives. It was tested on [130228] ハピメア.
Now I'm going to focus on the graphics files.

I think other games use different encryption. Once I'm done with graphics format, I'll check ハピメア-Fragmentation Dream- and クロノクロック.

**Comment by rr-** [comment]
Most of the image types are now supported. Background images are not yet supported. They need extra effort to work.

Before I focus on remaining images, I'm going to make sure [150424] Chrono Clock works too. (Chances are that it is encrypted differently from 「ハピメア」).

**Comment by rr-** [comment]
Chrono Clock uses later CPZ version, i.e. CPZ6. This is going to take a while.

**Comment by EAxp3** [comment]
Fantastic, Grand.. Thanks for implementation
I'll be waiting Chrono Clock......Thanks :) :+1:

**Comment by rr-** [comment]
Alright, everything should be good:

- Archives: CPZ5 variant 1, CPZ5 variant 2 and CPZ6
- Images: PB3 variant 1, 2, 3, 5 and 6 (I didn't see 4 anywhere)
- Audio: Vorbis OGG
- Scripts: PS2 (decompression only - they're still in compiled form)

Tested on:

- [Purple Software] [130228] Hapymaher
- [Purple Software] [150424] Chrono Clock
- [Purple Software] [150724] Hapymaher - W Pack
- [Purple Software] [150724] Hapymaher -Fragmentation Dream-

Happy unpacking!

![ev_mak01c](https://cloud.githubusercontent.com/assets/1045476/11863947/d8639348-a498-11e5-956e-73ac12386c2f.png)

**Comment by Aeka-Shiraki** [comment]
Hello sorry for the necro, I would like to know how to extract the compiled scripts for Chrono Clock please, thanks in advance.
