### ISSUE TITLE
HI, Please add support GAME .LPK

### ISSUE THREAD

**Issue by EAxp3** [vn-tools/arc_unpacker#23]
Please add: keys
 archive .LPK
GAME:[ [150227][WHITESOFT] さくらシンクロニシティ](https://vndb.org/v16215)

[tool-game not support](http://asmodean.reverse.net/pages/exnllpk.html)

sys
B5 B6 91 AE 5C ED 42 9D
chr
4E 99 C8 7D 99 24 E4 B6
pic
36 16 9D C6 69 B3 7D 38
data
C8 AA 4D 2D AE 75 5D E1

Thanks :)

game tool support game: [modified](https://www.youtube.com/watch?v=glc00KtxLRQ)
![lpk](https://cloud.githubusercontent.com/assets/15073580/12133987/670ff01c-b3f0-11e5-95f1-0080bf48ab4a.PNG)

:( :( :( :(

**Comment by rr-** [comment]
Now that I'm done with enhancing support for entis, I can work on this engine. I'll start tomorrow.

**Comment by EAxp3** [comment]
OK thanks.. :) :+1: 

Thanks for support: 3rd Eye-Sorcery Jokers
:) ;)

**Comment by rr-** [comment]
Done. Nightly build should be available in about 3 hours. Use with `--plugin=sakura-sync` switch.
