### ISSUE TITLE
Request support for protected .xp3 files.

### ISSUE THREAD

**Issue by NhKPaNdA** [vn-tools/arc_unpacker#27]
These games extract the iles from the .xp3 files but are innacessible due to protection.

- [x] Aniki no Yome-san Nara - https://vndb.org/v12914
- [x] Oku-sama wa Moto Yariman - https://vndb.org/v11575

These have corresponding .xp3.sig files if that means anything.

Games with just protected .xp3 files.

- [x] Seieki Tairyou Chuunyuu! 5 - https://vndb.org/v7177
- [x] Omoikkiri! Seieki Tairyou Chunyuu! - https://vndb.org/v4993

**Comment by rr-** [comment]
Resolved in c1f99b09e8b1a3fde99d89c9c089ef9394ce70f7, 0cd0bd4006df2743f9aa7d961fd9f0ecf93fa50f and 9e5919fd2389d9ebbc5255fce69d866c53f1606a
