### ISSUE TITLE
About nitro+ *.npk (new format)

### ISSUE THREAD

**Issue by mireado** [vn-tools/arc_unpacker#29]
nitroplus using new format on new 凍京NECRO(TokyoNecro).
![Imgur](http://i.imgur.com/S78Yxci.png)

Can you please support these format in later?

I attached some file on this address.
http://www.mediafire.com/?0rupvjuzz8jo0
(I want it could be a small help >_<// not including cg.npk/3d.npk/voice.npk)

Thank you >_<

**Comment by rr-** [comment]
Done
