### ISSUE TITLE
Game request: [Alcot Honey Comb][090417]Shinigami no Kiss wa Wakare no Aji

### ISSUE THREAD

**Issue by NhKPaNdA** [vn-tools/arc_unpacker#33]
Using --fkey or --gameexe doesn't work for Shinigami no Kiss wa Wakare no Aji.

Vndb:https://vndb.org/v1660

**Comment by rr-** [comment]
Is it the 2009 version or the 2013 one?

**Comment by NhKPaNdA** [comment]
Didn't know there was a popular edition. This is for the 2009 version.

**Comment by rr-** [comment]
Done:

- 767af77c419660199783e2508c14a92135ed314c: dec/qlie/pack: add --no-external-keys
- 4dd5452a1018b4e4c14bede55f3199be990c9571: docs: add [Alcot Honey Comb][090417]Shinigami no Kiss wa Wakare no Aji

Example image:

![sel](https://cloud.githubusercontent.com/assets/1045476/19288546/d4695a02-9006-11e6-86f1-af146aa70e42.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.
