### ISSUE TITLE
Help, please add support GAME: minori (罪ノ光ランデヴー) 2016/02/26

### ISSUE THREAD

**Issue by EAxp3** [vn-tools/arc_unpacker#35]
New Game 2016/02/26
Please add support Files

information: GAME:
[url1](http://www.getchu.com/soft.phtml?id=878766)
[url2](https://vndb.org/v17872)

I'm downloading process: GAME

Download Game: [罪ノ光ランデヴー](http://www.anime-sharing.com/forum/torrents-47/japanese-467265/)

more games: [new games](http://girlcelly.blog.fc2.com/)

thanks I hope you can help :)

**Comment by rr-** [comment]
Extended discussion on morkt/GARbro#18

**Comment by rr-** [comment]
Closing for now, we'll see if the tables turn in the future in our favor.
