### ISSUE TITLE
Premature end of file for Tokyo Necro's `cg.npk`

### ISSUE THREAD

**Issue by rr-** [vn-tools/arc_unpacker#36]
This problem doesn't occur on Linux, however, it's present in nightly Windows builds.
Probably it has to do with the fact that the file in question is over 5GB since other files work fine.

The first thing to check would be to verify `sizeof(size_t)` which is used all over the place for file offsets. If it's 32-bit only, we're screwed and need to change `size_t` to something else everywhere. Further more if Windows implementation of `fseek` uses 32-bit integers, we're screwed even more and probably need to use `fseeko` or `_fseek_whatever`.

**Comment by sst311212** [comment]
Hi there, any change to compile this program to 64bits?

**Comment by rr-** [comment]
The issue is being worked on on `off` branch

**Comment by sst311212** [comment]
Thanks, hope you can release next version soon.

**Comment by rr-** [comment]
Done - tested on gcc, clang, mingw-w64, cygwin and msvc. Fix should be ready in tonight's build.
