### ISSUE TITLE
Game request: [Campus][151225]Tenmon Dokei no Aria

### ISSUE THREAD

**Issue by fdtggf** [vn-tools/arc_unpacker#39]
I very want to save this game tachie
But i can't find any extract tool can extract this game in internet
So i need your help
Can you supprot to extarct this game?
Thank You!

This game look like using maliesystem engine
But ziped file is in data.dat not *.lib(one largest file)
Game data is uploaded

Information:
http://www.campus.gr.jp/product/orloi_aria/index.html
https://vndb.org/r43080
http://www.getchu.com/soft.phtml?id=874045

Game data:
https://mega.nz/#!BVBVjZBK!MmkZUsdRKzAfijtXUU43nGrswjK3QcBc8Ir0tkkiSbE

**Comment by rr-** [comment]
Done

- https://github.com/vn-tools/arc_unpacker/commit/e8fa6965c9105d8990aa9dea0d17128ac3c53792
- https://github.com/vn-tools/arc_unpacker/commit/094b63dd47409a416551ffc974aeb347c5670b05

Changes should appear in tonight's build: https://tmp.sakuya.pl/au/

**Comment by fdtggf** [comment]
Thank's your help


從三星手機發送

-------- 原有訊息 --------
由： Marcin Kurczewski <notifications@github.com> 
日期： 2016-09-04  22:55  (GMT+08:00) 
至： vn-tools/arc_unpacker <arc_unpacker@noreply.github.com> 
抄送： fdtggf <tonygoodboyqoo@gmail.com>,Author <author@noreply.github.com> 
主題： Re: [vn-tools/arc_unpacker] Game request: [Campus][151225]Tenmon Dokei no Aria (#39) 
 
Done

e8fa696
094b63d
Changes should appear in tonight's build: https://tmp.sakuya.pl/au/
