### ISSUE TITLE
Game request: [Dogenzaka Lab][160412]Dandy Shot

### ISSUE THREAD

**Issue by marcussacana** [vn-tools/arc_unpacker#40]
Can add support to this otoge?
http://store.steampowered.com/agecheck/app/447190/
You can use a retail copy, the cracked steam_api.dll of the 3DM works fine.... only change the game id to 447190

**Comment by rr-** [comment]
https://vndb.org/v15250

**Comment by rr-** [comment]
Note to self: `Hlk9D28p`

**Comment by rr-** [comment]
Done

- 2321bddd920bde7c0fc010372587abe2a0d2d04b
- 304f5d30edbb8bb106109c7f3858b75b7546623c
- b9732d4b606ef423c54d59ad067a54d9b5065593

Changes should appear in tonight's build: https://tmp.sakuya.pl/au/

**Comment by marcussacana** [comment]
thx
