### ISSUE TITLE
.WADY: Error decoding (Data size mismatch).

### ISSUE THREAD

**Issue by partial-s** [vn-tools/arc_unpacker#43]
![qq 20160515224120](https://cloud.githubusercontent.com/assets/16934954/15274873/fcbf3936-1aef-11e6-9ff1-09bcbdaec58e.png)

Sample WADY file: [M02.zip](https://github.com/vn-tools/arc_unpacker/files/265043/M02.zip) (7.8 M)
Extracted from: 幻聖神姫LINEAGE, which has the archive files with extension of "*.med".
Command I use: arc_unpacker.exe -d ...\M02
OS: Windows

**Comment by rr-** [comment]
I don't think it's Ivory/WADY, since the developer is Triangle, which is completely different company.
So the files get misdetected as WADY, while in reality there's no support for this particular format yet.

I'll see what I can do about this.

**Comment by SYNDIG1** [comment]
Thanks for your help. /ω\

**Comment by rr-** [comment]
Some of `.med` files should become extractable with tonight's nightly build. They contain character voice and henshin animations.
CG and BGM use different format I'll work on later.

**Comment by partial-s** [comment]
Glad to hear that, but then, Hmm... a new problem has appeared here.
I tried to extract `md_cv.med` and `md_jpg.med` (contain CV and henshin animations respectively), but neither of them decompressed with success, since the progress was stopped when decoding, as shown in the figure.
![qq 20160519164915](https://cloud.githubusercontent.com/assets/16934954/15388441/83c00248-1de4-11e6-974e-24e679038a76.png)

The version of arc_unpacker is `0.10-315-g4f7a320` nightly build.

**Comment by rr-** [comment]
Try with `--dec=dxlib/dx`

**Comment by partial-s** [comment]
Alright, I made such a stupid mistake... <3
It's working correctly now.

**Comment by rr-** [comment]
https://github.com/vn-tools/arc_unpacker/commit/bb71aef5799915cbf77adb46abbbf450b3e1e4b4 MED archives: :heavy_check_mark:
https://github.com/vn-tools/arc_unpacker/commit/8da8c6040b3a276c6cfa14df29fe02cfc778009d YB images: :heavy_check_mark:

Now all that's left is the music, which looks like some ADPCM.

**Comment by rr-** [comment]
https://github.com/vn-tools/arc_unpacker/commit/f9ed896c0951187de0a0dbe738f701625798c78f WADY audio: :heavy_check_mark: 

@partial-s please let me know if the new decoders work for you.

**Comment by partial-s** [comment]
Seemingly the decoder has been finished, I will try it when I get the latest nightly build. (Server still have not restored at present.)

Anyway, thanks for your hard efforts on this issue and this repository.

**Comment by rr-** [comment]
Since my ISP is being ridiculous, I've built the current version manually. Please let me know if it works for you. (I hope github doesn't block zipped executables)

[arc_unpacker-0.10-322-gbe2b0c0-bin.zip](https://github.com/vn-tools/arc_unpacker/files/288045/arc_unpacker-0.10-322-gbe2b0c0-bin.zip)

**Comment by partial-s** [comment]
Yes it could, extract the med and dx archives, and decode all the wady files correctly. <3
> To double-check, test with all games of Route2 which are using this type of encryption.

**Comment by rr-** [comment]
Thanks~
