### ISSUE TITLE
Game request: [Makura][151023]Sakura no Uta

### ISSUE THREAD

**Issue by Asgezar** [vn-tools/arc_unpacker#44]
So, old tools doesn't seems working so as arc_unpacker. Game uses bgi/ethornell v2
https://vndb.org/v562
http://www.makura-soft.com/sakuranouta/
Thanks.

**Comment by rr-** [comment]
Done, thanks to @Cqfuj

- dd7b0a6
- 95c4e2ed46999c0e2520142151ae795b85c2bbd7

Changes are available in nightly build: https://tmp.sakuya.pl/au/
