### ISSUE TITLE
Game request: [WendyBell][150626]Zoku Etsuraku no Tane

### ISSUE THREAD

**Issue by Lbzttt** [vn-tools/arc_unpacker#46]
https://vndb.org/v17061
Game download: https://sukebei.nyaa.se/?page=view&tid=1753808

Please support this game.
asmodean's exbelldat does not work for a newer WendyBell and TinkerBell games.

Thank you.

**Comment by rr-** [comment]
I made some progress - I can extract most of raw files. Unfortunately some of them are still corrupted.

I also found this: https://github.com/Ouroboros/Arianrhod/blob/master/Source/sources/Crass-source/cui/Csystem/Csystem.cpp

I should be able to finish this in a few days. Here's some teaser:

![20160809_234443_hss](https://cloud.githubusercontent.com/assets/1045476/17534805/45134ac2-5e8b-11e6-9b4e-157dfc44d0b5.png)

![20160809_234237_kne](https://cloud.githubusercontent.com/assets/1045476/17534776/1538e5d2-5e8b-11e6-942b-226431c5c9cd.png)

**Comment by shamashii** [comment]
It seems like either crass and as' tools need  specify an exe option, even though they have supported some Bell's game already.
If using crass directly without exe option, it could get some stand and background pics(after fixing header), but event pics always encrypted.

**Comment by AlchemistofAtlas** [comment]
Fixing header? I wouldn't know how to do that exactly, but if that works for character rips, it can be handy.

I see the teaser and I like what I see.

**Comment by rr-** [comment]
[Done](https://github.com/vn-tools/arc_unpacker/commits/master), the changes should appear in tonight's build in about 3 hours.

Example image:

![unk_1764](https://cloud.githubusercontent.com/assets/1045476/17652431/1b8cc56c-627c-11e6-8221-fb728098f7de.png)

**The switch for the new decoder is `--dec=wendy-bell/arc --plugin=zoku-etsuraku`.**

**Comment by AlchemistofAtlas** [comment]
Maybe it's just me, but after 3 hours, there haven't been any changes. The dec does not appear on the list.

**Comment by rr-** [comment]
By tonight's build I referred to nightly builds which are located here: https://tmp.sakuya.pl/au/

**Comment by Lbzttt** [comment]
Thank you! It worked great.

**Comment by rr-** [comment]
:ok_hand:

**Comment by AlchemistofAtlas** [comment]
Tells me bad value for  --dec
