### ISSUE TITLE
About: クロノクロック's stand.cpz

### ISSUE THREAD

**Issue by CATION-M** [vn-tools/arc_unpacker#50]
So...How can I unpack stand.cpz?

**Comment by CATION-M** [comment]
e.g: アマツツミ

**Comment by ayasaki-hayate** [comment]
`--dec=purple-software/cpz6`

**Comment by CATION-M** [comment]
QUOTE:https://github.com/vn-tools/arc_unpacker/issues/49

What is --no-vfs switch? And how do I use it?

**Comment by rr-** [comment]
This disables "virtual file system" which is used by decoders to cross-reference other files.

**Comment by CATION-M** [comment]
Understand. Thank you very much.
