### ISSUE TITLE
Game request: multiple Luxury games

### ISSUE THREAD

**Issue by CATION-M** [vn-tools/arc_unpacker#51]
Information:
a) おお勇者よ、イってしまうとは情けない！
http://www.getchu.com/soft.phtml?id=859767

b) 魔王のくせに生イキだっ！ とろとろトロピカル！
http://www.getchu.com/soft.phtml?id=813499

Asmodean's tools:
http://asmodean.reverse.net/pages/exmaotarc.html

Asmodean's tool has not been updated in 3 years.
Plz support these games.

Thank you.

**Comment by rr-** [comment]
@CATION-M could you please link to VNDB? Thanks

**Comment by CATION-M** [comment]
a) おお勇者よ、イってしまうとは情けない！
https://vndb.org/v17769

b) 魔王のくせに生イキだっ！ とろとろトロピカル！
https://vndb.org/v15360

**Comment by rr-** [comment]
「おお勇者よ、イってしまうとは情けない！」is done and will appear in tonight's build (01:05 UTC).

「魔王のくせに生イキだっ！ とろとろトロピカル！」 uses Themida which is way over my level.

**Comment by CATION-M** [comment]
OK. Thank you so much.

**Comment by rr-** [comment]
Progress update - I managed to obtain the key which is `qkh873z1`. Now I need to figure out the compression or lack thereof. Doing so without game code is going to be difficult.

**Comment by rr-** [comment]
Hmm, maybe some of their old games from shed some light... if they're older, they might be less protected, and thus be debuggable.

@CATION-M do you have any games that have `aInfo.db` file? If so, could you list them here?

**Comment by rr-** [comment]
OK, the compression is the same as in asmodean's `exmaotarc` which I have initially overlooked in the opening post. Support for 「魔王のくせに生イキだっ！ とろとろトロピカル！」 should be complete - just remember to pass additional CLI switches with game key etc.

Please let me know if the recent changes work for you once the nightly build is complete.

**Comment by CATION-M** [comment]
Thank you so much!!!!
If have change, I'll immediately notify you. :)

**Comment by rr-** [comment]
The important part is whether you can open the files in the explorer.
When it says PNG is not recognized, it means there's nothing further to decode. That's poor choice of words, but in the end, the files should be there. Please check them.

**Comment by CATION-M** [comment]
Thank for your reply. 

This's sample of my unpacked: https://mega.nz/#!9FJnmL7Y

I can't open it.

**Comment by rr-** [comment]
Ok, which game? Also the file you linked is encrypted...

**Comment by rr-** [comment]
@CATION-M this just a guess, but have you supplied correct command line switches like I asked to?

>just remember to pass additional CLI switches with game key

They're described in the game list:
https://rawgit.com/vn-tools/arc_unpacker/master/GAMELIST.htm#luxury

**Comment by CATION-M** [comment]
@rr- I tried to 「--dec=tactics/arc --arc-key=qkh873z1 --arc-pack=variable-lzss」&「--dec=tactics/arc --arc-key=qkh873z1」...But I didn't succeed.

> e.g. arc_unpacker.exe "d:\g\a\01.arc" --dec=tactics/arc --arc-key=qkh873z1 --arc-pack=variable-lzss

Is there another method to use?

**Comment by rr-** [comment]
Hmm.. it looks good.. here's the full command I use:

```console
./build/arc_unpacker ~/vn/done/\[Luxury\]\[140829\]Maou\ no\ Kuse\ ni\ Namaiki\ da\!\ Torotoro\ Tropical\!/*.arc --arc-key=qkh873z1 --arc-pack=variable-lzss
```

Version `.0.10-349-gf1cd3ca`.

With this I'm able to unpack `b_01a.png` just fine:
![b_01a](https://cloud.githubusercontent.com/assets/1045476/16716150/a6817cc4-46f4-11e6-855a-9f32b0ebc9bb.png)

Maybe you've got different release that uses another key?

**Comment by rr-** [comment]
Wait a minute, the nightly builds are way too old!

**Comment by CATION-M** [comment]
@rr- Ah...I always thought that 「--dec=tactics/arc」 is a required parameter...

**Comment by rr-** [comment]
@CATION-M It's always good to pass `--dec` but often it's not necessary. Not passing it incurs the cost of format autodetection though.

I'm sorry, looks like the nightly builds were broken since 5fa452ef501e7b7a79db64e6ba44d285d605ba31 (about 2 weeks) - the ABI has changed in a way that incremental build didn't catch and it has been failing ever since. I cleaned the build directory and generated new build that includes the new decoders.

https://tmp.sakuya.pl/au/arc_unpacker-0.10-349-gf1cd3ca-bin.zip

**Comment by CATION-M** [comment]
@rr- I realized that the use of arc_unpacker and asmodean are different, and now I have succeeded.

Thank you. :)

**Comment by rr-** [comment]
:+1:
