### ISSUE TITLE
Game request: [Nitroplus][160630]Sonicomi: Communication with Sonico

### ISSUE THREAD

**Issue by Redyn** [vn-tools/arc_unpacker#52]
Hi. Can you please add support for the English version of Sonicomi by JAST USA? This version uses NPK2 files (note that this is different from the original Japanese release, which used NPA instead), but the game isn't supported yet. If I try unpacking the files using the Tokyo Necro plugin, I get a "Premature end of file" error message.

VNDB: https://vndb.org/v4234
I don't think the Japanese title is necessary, since this request applies to the localized version exclusively, but here it is just in case: ソニコミ

Thank you!

**Comment by rr-** [comment]
Uhm, Tokyo Necro plugin refers to [Tokyo Necro game](https://vndb.org/v13666). Why would you want to unpack it that way?

**Comment by rr-** [comment]
Done:

- https://github.com/vn-tools/arc_unpacker/commit/578ad704a2a141346d98c6b7e93327ec8bbd54d0
- https://github.com/vn-tools/arc_unpacker/commit/f47b5292fd4c9a18fbc6c9f14f78dfc17f731a5a

Changes should appear in tonight's build.

**Comment by Redyn** [comment]
No particular reason. I just tried it because there was no Sonicomi plugin yet, even though I wasn't expecting it to work.

Anyway, thanks for for the quick update! Works like a charm.
