### ISSUE TITLE
Game request: [AliceSoft][160129]Tsumamigui 3

### ISSUE THREAD

**Issue by CATION-M** [vn-tools/arc_unpacker#53]
VNDB: https://vndb.org/v18486

For this game, I can use the asmodean([exafa](http://asmodean.reverse.net/pages/exafa.html)) unpack *.afa, and use the westside([mankchcv](http://www.westside.co.jp/download/sale/20130712/mankchcv.txt)) converts *.qnt to *.png.

However, the game uses a new format: *.dcf
It is said that have a way for converts *.dcf to *.qnt. But I can‘t find.

Can you supprot the new format for converts? Thanks. :)

The samples and related tools:
[Download](https://mega.nz/#!UZxkgZKK!B5D7gBDYk67dqwB5hkA7eddwqmHVXer4VWsKDPbZhUw)

**Comment by rr-** [comment]
Added support for AFA v2
Working on DCF

**Comment by rr-** [comment]
Added support for DCF

Changes should appear in tonight's build (please check the build time.)

**Comment by CATION-M** [comment]
![image](https://cloud.githubusercontent.com/assets/20357011/16899964/c88815e6-4c47-11e6-9056-c6bd0ccf19b1.png)

Thanks!!!

**Comment by ms0647510** [comment]
@CATION-M 
Hello buddy~~
I try the method you said, but I got some problems......
Could you help me?
When I put "Tsumamigui3CG.afa" into exafa_v2.exe
It just responds like the screenshot below:
http://imgur.com/G71HMpV
It said "Could not open XXXX.qnt(invalid argument)" and shutdown.
Could you help me how to solve this problem?
Thank you~~
