### ISSUE TITLE
Game request: [Regista][160427]Root Double -Before Crime * After Days-

### ISSUE THREAD

**Issue by ffleader1** [vn-tools/arc_unpacker#54]
VNDB link: https://vndb.org/v5000
Developer: Regista

----
Something I have learned from the game:
The game store its data in the .cpk files. The .cpk files can be unpacked using quickbms with cpk.bms
http://aluigi.altervista.org/bms/cpk.bms
However, unpacking it will result in 3 types of file
- .cl5 (apparently background image or sprite files). I am not sure how to unpack it.
Sample: https://drive.google.com/file/d/0B9qXA8yclPg6WUdDdUswMnFYcDQ/view?usp=sharing
- .hca (sound/music files). I was capable of unpacking it using HCA_encoder.
Link: https://drive.google.com/file/d/0B9qXA8yclPg6MFlGZjk4Y1hrdUU/view?usp=sharing
- .xtx (apparently script file). I am not sure how to unpack it either.

**Comment by rr-** [comment]
Which release? I'm asking because I see many platforms used.

**Comment by ffleader1** [comment]
Oh sorry. Steam version

**Comment by ffleader1** [comment]
Also, why you have not released another stable version for months T.T
Build the .exe seems to be a big hustle, for me at least.

**Comment by rr-** [comment]
That's what nightly builds are for. I'm busy with other projects, too.

**Comment by rr-** [comment]
Good news CPK and HCA are already supported, bad news CG is not. It doesn't look to be encrypted, but it's scrambled - kind of like GIM. Maybe it's headerless GIM. Will investigate later

![20160730_171508_pxf](https://cloud.githubusercontent.com/assets/1045476/17271339/464b6074-5679-11e6-967b-1ed2420e4942.png)

**Comment by rr-** [comment]
Relased 0.11, thanks for the final push

**Comment by ffleader1** [comment]
:D :D

**Comment by rr-** [comment]
Added support for XTX images

Changes should appear in tonight's build (in roughly 12 hours): https://tmp.sakuya.pl/au/

Example unpacked graphic:

![unk_1811](https://cloud.githubusercontent.com/assets/1045476/17277020/48d7bb1a-5739-11e6-8a70-4e0625d2c1d0.png)

**Comment by ffleader1** [comment]
So, the xtx is the image files, not cl5? :<
Man, I felt stupid. :<

**Comment by VNGirl93** [comment]
Works mostly fine now, but there are still two issues.

The first one is that the files in sys.cpk aren't decoded. Examining them with my untrained eyes revealed nothing other than that one of the files seems to be a shader. They don't even appear to have headers of any kind. I would assume this archive is where the UI images are located. The only other possible locations would be sn.bin and the executable, both of which are even smaller.

The second one is that the two font atlases (the only two .xtx files that aren't inside a .cpk file) are decoded incorrectly. They're not totally glitched, but clearly shouldn't look like this.

**Comment by rr-** [comment]
The font files are interesting. The way `arc_unpacker` converts them is 100% consistent with the way the game unpacks it internally just before passing it to DirectX.

There are two options:

- DirectX unscrambles the texture somehow (I doubt that; the same function is called for other XTX image variants and they work fine)
- The game unscrambles the bitmap on its own, in which case it's not a part of XTX image

**Comment by rr-** [comment]
I found out how the fonts are encoded. It's not BGR565, it's Gray4... and the glyphs are encoded spatially like this:

```
121212121212
343434343434
121212121212
343434343434
121212121212
343434343434
121212121212
343434343434
              |    | || 1 byte
              |    '--' 2 bytes
              '------' 4 bytes
```

Each of `1`, `2`, `3` and `4` symbolizes one pixel belonging to glyph 1, 2, 3 or 4.

Whether this is part of XTX or Cri or game, I've no idea.
Would appreciate some more samples of format 2 XTX images.

**Comment by rr-** [comment]
Alright I decoded the fonts and here they are:

![font48](https://cloud.githubusercontent.com/assets/1045476/19222231/c82883a8-8e53-11e6-8379-73c01ec05c1c.png)
![font48_eng](https://cloud.githubusercontent.com/assets/1045476/19222230/c827ad3e-8e53-11e6-8308-341d09e6a9a6.png)

but I won't be including this patch upstream cause it's way too hacky (block size = 48, quadruple width...). There's no way this works outside these specific fonts.

```
diff --git a/src/dec/cri/xtx_image_decoder.cc b/src/dec/cri/xtx_image_decoder.cc
index ecaa6bf..d4b8f20 100644
--- a/src/dec/cri/xtx_image_decoder.cc
+++ b/src/dec/cri/xtx_image_decoder.cc
@@ -80,19 +80,39 @@ static bstr read_tex_0(const Header &header, io::BaseByteStream &input_stream)
 
 static bstr read_tex_1(const Header &header, io::BaseByteStream &input_stream)
 {
+    const auto block_size = 48;
+    u8 intensity_map[] = {
+        0b00000000, 0b00010001, 0b00100010, 0b00110011,
+        0b01000100, 0b01010101, 0b01100110, 0b01110111,
+        0b10001000, 0b10011001, 0b10101010, 0b10111011,
+        0b11001100, 0b11011101, 0b11101110, 0b11111111,
+    };
+
     const auto input = input_stream.read(header.aligned_canvas_size() * 2);
-    bstr output(header.canvas_size() * 2);
+    bstr output(header.aligned_canvas_size() * 4);
     for (const auto i : algo::range(header.aligned_canvas_size()))
     {
-        const auto x = get_x(i, header.aligned_width, 2);
-        const auto y = get_y(i, header.aligned_width, 2);
-        if (y >= header.height || x >= header.width)
+        const auto abs_x = get_x(i, header.aligned_width, 2);
+        const auto abs_y = get_y(i, header.aligned_width, 2);
+        if (abs_y >= header.height || abs_x >= header.width)
             continue;
+
         const auto src = i * 2;
-        const auto dst = (x + y * header.width) * 2;
-        output[dst + 1] = input[src];
-        output[dst] = input[src + 1];
+        const auto block_x = (abs_x / block_size) * block_size;
+        const auto block_y = (abs_y / block_size) * block_size;
+        const auto x = abs_x % block_size;
+        const auto y = abs_y % block_size;
+        const auto target_y = block_y + y;
+        const auto target_x1 = block_x * 4 + x;
+        const auto target_x2 = block_x * 4 + x + block_size;
+        const auto target_x3 = block_x * 4 + x + block_size * 2;
+        const auto target_x4 = block_x * 4 + x + block_size * 3;
+        output[target_x1 + target_y * header.width*4] = intensity_map[input[src] >> 4];
+        output[target_x2 + target_y * header.width*4] = intensity_map[input[src] & 0xF];
+        output[target_x3 + target_y * header.width*4] = intensity_map[input[src + 1] >> 4];
+        output[target_x4 + target_y * header.width*4] = intensity_map[input[src + 1] & 0xF];
     }
+
     return output;
 }
 
@@ -177,10 +197,10 @@ res::Image XtxImageDecoder::decode_impl(
     if (header.format == 1)
     {
         return res::Image(
-            header.width,
+            header.width * 4,
             header.height,
             read_tex_1(header, input_file.stream),
-            res::PixelFormat::BGR565);
+            res::PixelFormat::Gray8);
     }
 
     if (header.format == 2)
```

**Comment by rr-** [comment]
I've examined `sys.cpk` and it contains a few UI graphics, sound files (the ones that play in the UI) and compressed tiny bits and pieces each of which is encoded differently (= PITA). The ratio of value to effort is too low to bother.

**Comment by VNGirl93** [comment]
Is there any easy way to identify Format 2 XTX images? Because I honestly don't really understand what you mean. If you're talking about images that look scrambled, the two font images are the only ones Root Double has.
If it helps, XTX is apparently a common texture format in Xbox 360 games. Some modding communities for the occasional PC port that still uses this format have reversed it, but their tools don't work with the XTX images in Root Double, so it seems the format has been altered recently. That, or it's a completely different format that just so happens to have the same extension.

**Comment by rr-** [comment]
The "format 2" XTX can be told from other XTX images by checking the byte
right after "xtx\x00" signature within the file. If its 0x02, it's format
2. For details please consult the decoder itself:

https://github.com/vn-tools/arc_unpacker/blob/master/src/dec/cri/xtx_image_decoder.cc#L157-L159
