### ISSUE TITLE
Game request: [Heiantei][160324]Aniyome Kyouka-san to Sono Haha Chikako-san ~Bijin Tsuma to Bijukubo to Issho~

### ISSUE THREAD

**Issue by AlchemistofAtlas** [vn-tools/arc_unpacker#55]
VNDB link: https://vndb.org/v18803
Developer: Heiantei
Release date: 2016/03/24
Original title: 兄嫁京香さんとその母千佳子さん～美人妻と美熟母といっしょ～
English title (if available): 

Hello. I'd like to request to support this game. Unfortunately the closest I've gotten to is ripping the files encrypted, but the elements cannot be seen.

Files are: dPi.dat (I think these are the CG/char sprites), includes a dPih.dat file related to it.
dSo.dat/dSoh.dat, which are music files.

There's another game I'm interested in requesting as well, but I also would request the game Lbzttt is requesting as well.

**Comment by AlchemistofAtlas** [comment]
I assume you were waiting for the other part to be released, it's now up to cover both.

**Comment by shamashii** [comment]
The structure of file seems like [150626] [WendyBell] Zoku Etsuraku no Tane, see issue 46

**Comment by rr-** [comment]
I'll work on this this weekend, thanks @shamashii

**Comment by rr-** [comment]
Done:

- 7a3dd436338275a5b8cffe7879f1c143cbae3c86
- e6a3a6b21ad4dead6db2f608be72b74bd8bb3428
- 43b03540b91bcd0c5dd447d4858aede1afd2983c
- 2c32ce71cbf1e80aaddb7d01de473c3889033bc0

Example image:

![unk_653](https://cloud.githubusercontent.com/assets/1045476/18593464/d00cdcd8-7c3b-11e6-84f4-5ef1836c9455.png)

The changes should appear in [tonight's build](https://tmp.sakuya.pl/au/) around 1 AM UTC.

**Comment by AlchemistofAtlas** [comment]
Ok. Works now. Thank you.
