### ISSUE TITLE
Game request: [Almond Collective][160305]Panty pilferers and mermaid in school swimwear

### ISSUE THREAD

**Issue by joafe** [vn-tools/arc_unpacker#57]
## Game info

Developer:  アーモンドコレクティブ
Release date: 2016/03/05
Original title: パンツ泥棒たちとスク水マーメイド
English title: Panty pilferers and mermaid in school swimwear
DLsite work number: RJ172521/RE172521

## Details

Would like to extract game resources (videos, etc.) from the "Data.pac" file.

**Comment by rr-** [comment]
So far got the file table, working on the file contents

**Comment by rr-** [comment]
[Done](https://github.com/vn-tools/arc_unpacker/commit/9e5330b1547fa545b07633dbc812846f42ebf385), changes should appear in [tonight's build](https://tmp.sakuya.pl/au/) in about 2 hours

Example image:

![moviebuttons](https://cloud.githubusercontent.com/assets/1045476/17465697/7c3f6df6-5cff-11e6-938e-b6d8ace4d5cd.png)

**Comment by joafe** [comment]
Great to hear!
