### ISSUE TITLE
Game request: [Almond Collective][131103]Ojiki to mei to

### ISSUE THREAD

**Issue by joafe** [vn-tools/arc_unpacker#58]
## Game info

Developer: アーモンドコレクティブ
Release date: 2013/11/03
Original title: 叔父貴と姪と
DLsite work number: RJ124336
## Details

Would like to extract game resources (videos, etc.) from the "Data.pac" file.

**Comment by rr-** [comment]
[Done](https://github.com/vn-tools/arc_unpacker/commits/master), changes will be available in tonight's build.

Example image:
![setting](https://cloud.githubusercontent.com/assets/1045476/17528058/117d5350-5e6e-11e6-9251-fda8bc4f5332.png)

Please note that both this game and the game from #57 now need `--pac3-key` which is respectively `OjikiMei` for 叔父貴と姪と and `Mermaid!` for パンツ泥棒たちとスク水マーメイド.

**Comment by joafe** [comment]
There seems to be a problem with my file/path name?

~~~~
C:\Users\j\Desktop\d>arc_unpacker --dec=almond-collective/pac3 --pac3-key=OjikiM
ei Data.pac
[task 0] Data~.pac: initial recognition...
[task 0] Data~.pac: guessing decoder among 1 decoders...
[task 0] Data~.pac: recognized as almond-collective/pac3.
[task 0] Data~.pac: recognition finished with errors (boost::filesystem::path co
decvt to wstring: error)
Executed 1 tasks in 0.03s (1 problem, 0 saved files)
~~~~

**Comment by rr-** [comment]
Hmm, it works here:

```console
rr-@tornado:~/src/maintained/arc_unpacker$ ./build/arc_unpacker --dec=almond-collective/pac3 --pac3-key=OjikiMei ~/vn/done/\[Almond\ Collective\]\[131103\]Ojiki\ to\ mei\ to/Data.pac
[task 0] Data~.pac: initial recognition...
[task 0] Data~.pac: guessing decoder among 1 decoders...
[task 0] Data~.pac: recognized as almond-collective/pac3.
[task 0] Data~.pac: archive contains 87 files.
[task 87] Data~.pac: decoding "Data/SE/TitleCall.ogg"...
[task 87] Data~.pac: decoding of "Data/SE/TitleCall.ogg" finished.
(...)
```

can you upload the exe somewhere so we know we have the same release?

**Comment by rr-** [comment]
OK, the issue was with path encoding. New version is available [here](https://tmp.sakuya.pl/au/arc_unpacker-0.11-14-g8716010-bin.zip).

**Comment by joafe** [comment]
Worked like a charm, thanks.
