### ISSUE TITLE
Game request: [Almond Collective][110507]Bloomers Lesson

### ISSUE THREAD

**Issue by joafe** [vn-tools/arc_unpacker#59]
## Game info

Developer: アーモンドコレクティブ
Release date: 2013/05/07
Original title: ゴリマッチョとブルマレッスン
English title: Bloomers Lesson
DLsite work number: RJ076908

## Details

Would like to extract game resources (videos, etc.) from the "Data.pac" file.

**Comment by rr-** [comment]
The game uses PAC2 rather than PAC3. The encryption is still used but looks much simpler.

**Comment by rr-** [comment]
[Done](https://github.com/vn-tools/arc_unpacker/commits/master), the changes should appear in tonight's build in about 6 hours.

Example image:

![config](https://cloud.githubusercontent.com/assets/1045476/17530332/615adb50-5e77-11e6-9f08-c0f616ee5e95.png)

The switch for the new decoder is `--dec=almond-collective/pac2`.
