### ISSUE TITLE
Game request: [Grand Cross][141230]Maki Fes!

### ISSUE THREAD

**Issue by Asonn** [vn-tools/arc_unpacker#60]
## Game info

VNDB link:  https://vndb.org/v16484
Developer:  Grand Cross
Release date: 2014/12/30
Original title: マキフェス！
English title (if available): Maki Fes!

## Details
Would like to extract all the war files (images, scripts ect.), so I could translate the game ^^

**Comment by rr-** [comment]
WAR is going to take some time :( I'll take a look next week

**Comment by Porygon2** [comment]
Seeing the fix of #66, I had a shot at this again and got all files <~4KB to extract correctly with this:
```C++
	plugin_manager.add(
        "makifes",
        "Maki Fes!"
        "Maki Fes",
        []()
        {
            auto p = std::make_shared<warc::Plugin>();
            p->version = 2500;
            p->entry_name_size = 0x20;
            p->region_image = read_etc_image("region.png");
			p->logo_data = read_etc_file("logo8.jpg");
            p->initial_crypt_base_keys
                = {0xF6DF81DF, 0x1BDE29DE, 0x000005DE, 0, 0};
			p->flag_pre_crypt
                = p->flag_post_crypt
                = warc::get_flag_crypt1(read_etc_file("flag.png"), 0x12BDB19B);
            p->crc_crypt = warc::get_crc_crypt(read_etc_file("table4.bin"));
            return p;
        });
```

All files larger than that have the first symbol in their filename replaced by an underscore when extracted and show garbage contents.
Is there any similar fix for this, given this new information?

# Attachments
## Logo image
logo8.jpg:
![logo8](https://cloud.githubusercontent.com/assets/17053863/18419229/52e0233e-7856-11e6-88ee-bd5effe4c2a4.jpg)

## Game data
MAKIFES_T.WAR (script archive) and MAKIFES.EXE (game executable):
[MAKIFES.zip](https://github.com/vn-tools/arc_unpacker/files/466129/MAKIFES.zip)

**Comment by rr-** [comment]
@Porygon2 thanks. I missed your comment, I just pushed relevant changes. The game uses custom decrypting routine which is similar to `flag_crypt1` but uses different PNG file, and the algorithm itself is different too (the routine is loaded to the memory dynamically).

@Asonn sorry for the delay.

Done:

- a0706cfd26e4bbba250545fc04f8aa84d44033cf
- 370e1944daa698256f38edd73f2f2c408a07e847
- e1ec32aa56e1e628a52d90f1d050bce9d0db763e (new kind of S25 images)

Example image:

![mk13 1](https://cloud.githubusercontent.com/assets/1045476/18419425/9447c512-785a-11e6-9c1a-aa8717945cd0.png)

The changes should appear in [tonight's build](https://tmp.sakuya.pl/au/) around 1 AM UTC.

**Comment by Asonn** [comment]
Thanks :D
