### ISSUE TITLE
it does can repack by using your 'scr' ??

### ISSUE THREAD

**Issue by yorutoitskuki** [vn-tools/arc_unpacker#61]
for example, 
'xp3' can unpack and can repack by using 'kirikiri engine'
so i did turn clothes to naked, (yes, i did 'nude patch')
and Now i want do 'nude patch' on "amatsu-tsumi(アマツツミ) made from 'purple software'"
several years ago
named 'rapatch' made 'tachie' to do 'nude patch'
and he did 'nude patch' on hapymaher(ハピメア) made from 'purple software'
but did not work on hapymaherFD (ハピメア Fragmentation Dream)
and He just disappeared, nobody know why
ok back to the my request
is it can repack by using Your scr ??
if it can I will try learn C+ for make 'nude patch' for 'purple software'

-------
about the 'tachie'
it recognize file such as xp3, cpz, whatever it can
and make list.csv with file name
and re-write list.csv to whatever you want, such as clothes to naked
and put list.csv in tachi.exe then it replace as list.csv
and play the game

**Comment by rr-** [comment]
>is it can repack by using Your scr ??

Sorry, but I don't understand. `arc_unpacker` does not support repacking files, only extracting. Extracting of ハピメア-Fragmentation Dream- is already supported, so I'm not sure what do you want me to do here.

すみませんが分かりません。arc_unpackerはアーカイブを作るをサポートしていません。「ハピメア-Fragmentation Dream-」の解凍は既にサポートされています。どのようすればいいでしょうか。
