### ISSUE TITLE
Game request: [Umemaro 3D][160825]Cheeky Girl

### ISSUE THREAD

**Issue by joafe** [vn-tools/arc_unpacker#64]
## Game info

Developer: 梅麻呂3D (Umemaro 3D)
Release date: 2016/08/25
Original title: いまどきのおんなのこ
English title: Cheeky Girl

## Details

Would like to extract videos from the exe.

**Comment by joafe** [comment]
As it turns out, everything was extracted to /Local/Temp when the executable was running, and deleted afterwards. I guess no need to bother you with this.

**Comment by rr-** [comment]
+1, I don't like extracting `.exe`s very much
