### ISSUE TITLE
Game request: [MAGES][160908]Stein;Gate (Steam version)

### ISSUE THREAD

**Issue by ffleader1** [vn-tools/arc_unpacker#65]
VNDB link: https://vndb.org/v2002
Developer: MAGES
Release date: 9/9/2016
Original title: Stein;Gate
English title (if available): Stein;Gate

game request

File example: https://drive.google.com/file/d/0B9qXA8yclPg6YjVacWZGVDcxTTg/view?usp=sharing
File .mpk
Also, I know you don't do game repack, but for this game (cuz it's Stein;Gate), I just want to test, mod its graphic so if you can give a nice little repack binary file for this game, that would be great.

**Comment by ffleader1** [comment]
Btw, I tried the propeller tools but it does not work T.T

**Comment by ffleader1** [comment]
Also, if you need more example files, I will got you covered

**Comment by ffleader1** [comment]
Background file:
https://drive.google.com/file/d/0B9qXA8yclPg6TFpfTEp2NEtkSHM/view?usp=sharing

**Comment by ffleader1** [comment]
You would normally reply very quick T.T

**Comment by rr-** [comment]
1. Posting raw files doesn't help.
2. [Propeller](https://vndb.org/p253) engine has nothing to do with [Nitroplus](https://vndb.org/p42) nor [5pb](https://vndb.org/p146). MPK file extension is coincidental.
3. Apparently this game is already supported - what's wrong with using `--dec=mages/mpk`?

**Comment by ffleader1** [comment]
1. Sorry T.T I will keep that in mind later T,T
2. Yeah, I was just grasping at straw T.T Sorry again.
3. I did not know T.T When I check your list, I only see the nitro version of Stein;Gate. And when I search mages, it returns no result, so I though this engine is new on Steam. Nvm, I will do research better from now on. Thank you. Closed.
![image](https://cloud.githubusercontent.com/assets/15016720/18412487/e8d69712-77b9-11e6-8fd9-8aab12af33fc.png)
