### ISSUE TITLE
Game request: [3rdEye][130628]Gensou no Idea ~Oratorio Phantasm Historia~

### ISSUE THREAD

**Issue by marcussacana** [vn-tools/arc_unpacker#66]
## Game info
VNDB link: https://vndb.org/v11881
Developer: 3rdEye
Release date: 2013 
Original title: 幻創のイデア～Oratorio Phantasm Historia～
Engine: Shiina

## Details
Some files i can extract without problem, but some others...
the arc_unpacker says: 
error decoding "??" (Failed to inflate zlib stream (invalid distance too far back near ??))
(?? is file name and a random value)

My Settings:
```
    plugin_manager.add(
        "gensou",
        "Gensou no Idea ~Oratorio Phantasm Historia~"
        "Gensou no Idea",
        []()
        {
            auto p = std::make_shared<warc::Plugin>();
            p->version = 2490;
            p->entry_name_size = 0x20;
            p->region_image = read_etc_image("region.png");
            p->logo_data = read_etc_file("logo4.jpg");
            p->initial_crypt_base_keys
                = {0xA79DBA45, 0xA9E7A868, 0xA84DA86A, 0, 0};
            p->flag_pre_crypt = warc::get_flag_crypt2();
            p->crc_crypt = warc::get_crc_crypt(read_etc_file("table4.bin"));
            return p;
        });
```
(srry my english)

**Comment by rr-** [comment]
Where did you get those numbers?

**Comment by rr-** [comment]
You almost got them right, but they're little endian, so initial crypt base keys are `{0x45BA9DA7, 0x68A8E7A9, 0x6AA84DA8, 0, 0}`. Plus there's new logo image used.

**Comment by rr-** [comment]
Done:

- e4795e3e9788d100f491f47872ff0c0c40b75027
- befd13d207c6c98e409f1cb73768a69ea0643b47

Example image:

![evf_40_02ad](https://cloud.githubusercontent.com/assets/1045476/18416730/75234262-781c-11e6-9a0a-cb85fab84e70.png)

The changes should appear in [tonight's build](https://tmp.sakuya.pl/au/) around 1 AM UTC.

**Comment by marcussacana** [comment]
i see, thanks.
