### ISSUE TITLE
Game request: [Valkyria][140926]Gachinko! B* Club Plus

### ISSUE THREAD

**Issue by AlchemistofAtlas** [vn-tools/arc_unpacker#67]
VNDB link: https://vndb.org/v15662
Developer: Valkyria
Release date: 2014/09/26
Original title: ガチンコ！ビッチクラブ
English title (if available): Gachinko! Bitch Club

Mainly I want this one because I can only exteact the event CG, but I also want the character rips, unfortunately, the only tool that can do that is private and can't be shared.

**Comment by rr-** [comment]
Please create separate issues for each game

**Comment by AlchemistofAtlas** [comment]
Ok, will do. Thank you.

**Comment by rr-** [comment]
The files are encoded in very stupid way, I'll take a look at other games from this publisher

**Comment by rr-** [comment]
*Finally* checked another game from this publisher, it's exactly the same which makes me happy, because I can hardcore many assumptions in the code and will work for more than one game. Shouldn't take much longer now.

**Comment by rr-** [comment]
Done:

- 27f9e8f567e445eb7afbc31e018fddf561655cc8: dec/valkyria/odn: initial support
- ed2a50977aa11664bd1aa884db48a13c5ee46d93: dec/valkyria/odn: support images
- 9ebcc59b84ade4410fa350029aae8a39667cd82f: docs: add [Valkyria][140926]Gachinko! Bitch Club Plus

Example image:

![cccc0070](https://cloud.githubusercontent.com/assets/1045476/19220998/925e8c5e-8e3a-11e6-8f83-18f8e055b82a.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by AlchemistofAtlas** [comment]
Well, there has been the problem the current build on the link you dropped hasn't appeared yet, this time I checked and the latest one is from October 8 instead, which I checked to be sure if it was, but the valkyria dec is not there yet.

**Comment by rr-** [comment]
Yeah I just woke up and seems like the build machine experiences the same problems as Travis (I don't experience this with clang on my development machine.)
I've already pushed the fix, now building the nightly manually.

**Comment by rr-** [comment]
It's here:
https://tmp.sakuya.pl/au/arc_unpacker-0.11-80-ga5ebedc-bin.zip
Sorry for the wait orz

**Comment by AlchemistofAtlas** [comment]
Ok, it worked now. Thank you.

**Comment by marconii2002** [comment]
Do not work witch [Valkyria] Seikishi Celsia ~Akuratsutaru Himegimi~ game

Odn files are properly extracted but image files are not properly decoded

**Comment by rr-** [comment]
That's another game altogether. Please open a separate issue for this rather than unbury unrelated issues.
