### ISSUE TITLE
Game request: [Tinkerbell][140523]Shukubo no Uzuki ~Hitozuma Miboujin no Nareta Karada to Amai Toiki~

### ISSUE THREAD

**Issue by AlchemistofAtlas** [vn-tools/arc_unpacker#68]
VNDB link: https://vndb.org/v14593
Developer: Tinkerbell
Release date: 2014/05/23
Original title: 淑母の疼き ～人妻、未亡人の熟れた身体と甘い吐息～

I hold a strong interest on this game (due to the lack of ways to rip it), and on its sequel, but as you asked me to do, I'm making a separate thread for this to be looked upon.

**Comment by rr-** [comment]
Done:

- 105f269
- ece3b13
- ec9ca39

Example image:

![unk_1793](https://cloud.githubusercontent.com/assets/1045476/18617268/1a847cbc-7dcc-11e6-9a88-65c98e9c2baa.png)

The changes should appear in [tonight's build](https://tmp.sakuya.pl/au/) around 1 AM UTC.

**Comment by AlchemistofAtlas** [comment]
Ok, it worked. Much appreciated.
