### ISSUE TITLE
Game request: [Tinkerbell][150918]Shukubo no Uzuki 2 ~Nareta Hitozuma kara Tadayou "Onna" no Iroka~

### ISSUE THREAD

**Issue by AlchemistofAtlas** [vn-tools/arc_unpacker#69]
VNDB link: https://vndb.org/v17264
Developer: Tinkerbell
Release date: 2015/09/18
Original title: 淑母の疼き2 ～熟れた人妻から漂う“女”の色香～

Same case as with the first game, I hold a strong interest for the ripping and the char images. Same case, separated the threads as you asked. Thank you.

**Comment by rr-** [comment]
Done:

- ece3b13cd233556a1a5ff68e067b4a7b4e758921
- 47d2ab0fdf1f5831d8d4ccac807739ce38ac36fc
- ad7a0d55dafc1815fe9db9c428b6db30cb8b5882

Example image:

![unk_0028](https://cloud.githubusercontent.com/assets/1045476/18617322/358ac38a-7dcd-11e6-88c0-8d9ff108634c.png)

The changes should appear in [tonight's build](https://tmp.sakuya.pl/au/) around 1 AM UTC.

**Comment by AlchemistofAtlas** [comment]
Ok, this one worked partially, While the event CG was fully ripped, char cg images weren't fully ripped.

**Comment by rr-** [comment]
Why do you think compression used by the game is the same as PNG compression?

**Comment by AlchemistofAtlas** [comment]
![snapshot1](https://cloud.githubusercontent.com/assets/20749122/18624111/519ade10-7e0a-11e6-97fe-8e867e3f1f36.png)
![snapshot2](https://cloud.githubusercontent.com/assets/20749122/18624110/519a2664-7e0a-11e6-9b51-7a689336a4ba.png)
![snapshot3](https://cloud.githubusercontent.com/assets/20749122/18624112/519c4e26-7e0a-11e6-9ca9-ee5a6477ddb6.png)
![snapshot4](https://cloud.githubusercontent.com/assets/20749122/18624115/51a0627c-7e0a-11e6-9a9a-1f15ed848703.png)
![snapshot5](https://cloud.githubusercontent.com/assets/20749122/18624113/519d38ae-7e0a-11e6-83f9-4b59a8dc538c.png)
![snapshot6](https://cloud.githubusercontent.com/assets/20749122/18624114/519fa9f4-7e0a-11e6-9732-8a2b5eaebd94.png)

If you notice, the char sprites don't come with other attires. This problem didn't happen with the rip for the first game, though.

**Comment by rr-** [comment]
I meant post a screenshot **from the game** that isn't in the unpacked files
Also please don't post NSFW images

**Comment by AlchemistofAtlas** [comment]
Much as I would love to put a screenshot, those available are NSFW in content (I believe undergarment enters in NSFW territory, I guess), but I can tell you they all have different attires. They have interchangeable attires, though (played the game last year, so, I might have forgotten a few things, but had to reinstall the game to further look). The safe ones I posted (but deleted to keep this SFW), should tell however that not all character sprites were ripped, if you compare zoomed in sprites with zoomed out ones, you'll notice facial expressions are missing as well.

**Comment by rr-** [comment]
Hmm, I'm pretty sure that all files are extracted. If a certain version of a given pose is missing, it's possible the game simply doesn't use it.

You can always send NSFW samples at rr-@sakuya.pl

**Comment by rr-** [comment]
We were both right: all files from the `.dat` archives were extracted and there were indeed files missing. Turns out the missing files reside in `.appendix` files that I have completely overlooked.

They're supported now:

- 47c2b75baaddc61a2477df62df3aaf51133f7615 dec/cyberworks: extract 'common' namespace
- cd8e7f7f0caea9a97d4df8fcdb7e460aad3c5132 dec/cyberworks/appendix: initial support
- d1aa7465ac8e5339198e1ed4576379a841835889 dec/cyberworks/common/algo: add 'w0' data type
- 5bcc870cdcf9b94d0dd96c1fbcbfd2e2c97bf8b8 docs: update [Tinkerbell][150918]Shukubo no Uzuki 2 ~Nareta Hitozuma kara Tadayou "Onna" no Iroka~

Example image:

![unk_00](https://cloud.githubusercontent.com/assets/1045476/18641878/c2f48c0c-7e9e-11e6-9417-d78003943b94.png)

The changes should appear in [tonight's build](https://tmp.sakuya.pl/au/) around 1 AM UTC.

**Comment by AlchemistofAtlas** [comment]
Wow, I had forgotten about the appendix files completely.

So, once the build is there, should I drag the appendix file and use the corresponding dec and plugin, correct?

**Comment by rr-** [comment]
Yep

**Comment by AlchemistofAtlas** [comment]
Ok, the extraction of the appendix files was successful. It's completed.

Thanks.

**Comment by Veshurik** [comment]
Hello, guys! I wonder how is it even possible to extract files from TinkerBell games?
I rarely see nowadays some people doing extracts at all.

Meanwhile, new game from TinkerBell releasing this December, demo version available already. Thanks!.

https://vndb.org/v32026
