### ISSUE TITLE
No decoder recognizes Ao no Kanata no Four Rhythm's .arc files

### ISSUE THREAD

**Issue by nakhistae** [vn-tools/arc_unpacker#71]
VNDB link: https://vndb.org/v12849
Developer: Sprite
Release date: 2014-09-03
Original title: 蒼の彼方のフォーリズム
English title (if available): Ao no Kanata no Four Rhythm

Just trying to extract the fonts and backgrounds if possible. 

The page of supported games lists Aokana as a supported game. This didn't seem to be the case. I tried to use the listed parameter "--dec=bgi/arc", but all attempts to unpack any arc file from Aokana failed. My game files should be fine since I also tried with a fresh install on my laptop. Both computers on Windows 7, using v0.11 of the unpacker.
Screenshot of Command Line Input/Output: https://i.imgur.com/h2H7k6c.png

**Comment by rr-** [comment]
Are you using the newest version?
https://tmp.sakuya.pl/au/

**Comment by nakhistae** [comment]
Earlier, I tried the latest nightly build as well as previous stable builds and no luck.

Just tried the nightly build again and still errors.

**Comment by nakhistae** [comment]
Tried the build you suggested (v0.11-65-g26f98fa), and it works fine!

The nightly I had, 0.11-13-g03648d6-bin.zip, was out of date, I guess.

**Comment by rr-** [comment]
I'll sort the files better in the nightly builds, cause right now they order is very confusing.
(They used to be presented nicely but I switched to another web server.)
