### ISSUE TITLE
Game request: [blue arrow garden][160921]Succubus Shelly 2

### ISSUE THREAD

**Issue by joafe** [vn-tools/arc_unpacker#72]
## Game info

Developer: blue arrow garden
Release date: 2016/09/21
Original title: 小悪魔シェリー2 ～新婚生活編～

## Details

Would like to extract game resources (videos, etc.) from the various "resourcexx.bin" files.

**Comment by rr-** [comment]
Done:

- 639a6566fed633fc34cea857d1700b1409e196f7: io/file: add mp4 to known extensions
- 37b870ee5d0f65ffc9b9663dc90e269db177b781: dec/bluearrowgarden/bin: initial support
- 073fd6e017e5c941eb3bcb529399a48bd3b804fd: dec/bluearrowgarden/images: initial support
- 1adee2c23cef3fc204b3d0657391de3f3b0b35cc: docs: add [blue arrow garden][160921]Succubus Shelly 2

Example image:

![title_logo](https://cloud.githubusercontent.com/assets/1045476/19223372/4c7e37d2-8e6e-11e6-938f-500edcbd5759.png)

(videos are unpacked as MP4)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.
