### ISSUE TITLE
Game request: [onomatope*Raspberry][160428]B* Nee-chan ga Seijun na Hazu ga Nai!

### ISSUE THREAD

**Issue by sst311212** [vn-tools/arc_unpacker#73]
VNDB link: https://vndb.org/v18781
Developer: onomatope*Raspberry
Release date: 2016/04/28
Original title: ビッチ姉ちゃんが清純なはずがないっ！
English title (if available): Bitch Nee-chan ga Seijun na Hazu ga Nai!
RioShiina system

**Comment by rr-** [comment]
Done:

- f84156cc1691dab33a6991f3c9180828a5162709: dec/shiina-rio/warc: add bitch-neesan plugin
- fff470d01912b7d265cc0ff1735a62ab4f9a41f6: docs: add [onomatope*Raspberry][160428]Bitch Nee-chan ga Seijun na Hazu ga Nai!

Example image:

![kd10_f_00](https://cloud.githubusercontent.com/assets/1045476/19202483/c2c57998-8cd2-11e6-9759-b63d91da749c.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by sst311212** [comment]
Many thanks, can I request more this system's games?

**Comment by rr-** [comment]
Regarding game requests: sure, go ahead (though I don't know when I have the time to do them)

I'll verify whether S25 images from ShiinaRio contain X,Y offsets; if they do, I'll offset the images with transparent area. But I wouldn't count on that, AFAIR the merging and the offsets is something that is solely handled inside the game scripts.

**Comment by rr-** [comment]
Yep - the only 8 bytes in S25 images that I ignore and could hold X, Y position are random garbage. Sorry. :(
