### ISSUE TITLE
Game request: [Front Wing][160428]Island

### ISSUE THREAD

**Issue by deltazechs** [vn-tools/arc_unpacker#75]
## Game info

VNDB link: https://vndb.org/v18498
Developer: Front Wing
Release date: 2016
Original title: アイランド
English title (if available): Island

## Details

Hi, was wondering if I could make a request here (really appreciated your work on unpacking Hatsuru Koto Naki Mirai Yori, by the way).  I am interested in getting to the cg and character sprites, and I believe it follows the same format of needing to unpack .int file first and then turning the hg3 files into images.  If it's not too much trouble, it'd be great if this software supports unpacking this game too, thanks!

**Comment by rr-** [comment]
Done:

- e25c56c5f93fd3832700f65bd5dc44423bd463ad: dec/cat-system/int: fix unencrypted archives
- 2083bbecefca610eca7a4505cf395e793515d4af: docs: add [Front Wing][160428]Island

Example image:

![sub001a](https://cloud.githubusercontent.com/assets/1045476/19251060/c7ccc370-8f3d-11e6-9a0c-12a322128ffb.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by deltazechs** [comment]
Thank you so much!
