### ISSUE TITLE
Game request: [WendyBell][140530]Cosplay Ecchi ~Layer Kana no Yuuutsu~

### ISSUE THREAD

**Issue by marconii2002** [vn-tools/arc_unpacker#76]
## Game info

VNDB link: https://vndb.org/v14627
Developer: WendyBell
Release date: 30-05-2014
Original title: こすぷれえっち ～レイヤー香奈の憂欝～
English title (if available): 

## Details

Can you add support for this game ?

**Comment by rr-** [comment]
Done:

- ee0a5ecef835fe7c5af9ce34ee08b3aefc464f3e: dec/cyberworks/dat: add cosplay-ecchi plugin
- 4b1cdbca342aad70b6195c2007a3ef285d9f48de: docs: add [WendyBell][140530]Cosplay Ecchi ~Layer Kana no Yuuutsu~

Example image:

![unk_1873](https://cloud.githubusercontent.com/assets/1045476/19281119/ffbf3cee-8fe8-11e6-98d3-aec84062709d.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.
