### ISSUE TITLE
Game request: [Tsumiki Soft][160226]Happening LOVE!! 

### ISSUE THREAD

**Issue by fdtggf** [vn-tools/arc_unpacker#77]
##  Game info

VNDB link: https://vndb.org/v18173
Developer: Tsumiki Soft
Release date: 2016-02-26
Original title: ハプニングLOVE!!
English title (if available): Happening Love!!

## Details
This game packed file is .lpk,it's probably use lucifen system.
But asmodean's  exnllpk is stopped update long time.
So I want you too help me too extract this game
Game data is here
[https://mega.nz/#!tJphQDiB!446UxNRn1k19a160h8xF0hNM3KgLCyk-suHPVmgcGcQ](url)

Thank you

**Comment by rr-** [comment]
Done:

- a7baeb4ba5bf4f7cdc0f0fd41c6d5156829c5eca: dec/lucifen/lpk: add happening-love plugin
- 94d97c1f72fc335db4b8da66a77fb2c1a1da4f25: docs: add [Tsumiki Soft][160226]Happening LOVE!!

Example image:

![ev75](https://cloud.githubusercontent.com/assets/1045476/19283748/5738dda4-8ff3-11e6-834a-73ff9f7a8bee.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by fdtggf** [comment]
Too fast,great job.
Thank's your help!!

2016-10-12 2:43 GMT+08:00 Marcin Kurczewski <notifications@github.com>:
