### ISSUE TITLE
Game request: [Valkyria][151023]Seikishi Celsia ~Akuratsutaru Himegimi~

### ISSUE THREAD

**Issue by marconii2002** [vn-tools/arc_unpacker#78]
## Game info

VNDB link: https://vndb.org/v17949
Developer: Valkyria
Release date: 23-10-2015
Original title: 聖騎士セルシア ～悪辣たる姫君～
English title (if available): 

## Details

Can you add support for this game ? 
Now odn files are properly extracted but image files are not properly decoded

**Comment by rr-** [comment]
I'll check this out today, will probably need to create `--plugin`.

**Comment by rr-** [comment]
Done:

- 735d9a9b829d42b05163dddb5a3ad0de9cd734ee: dec/valkyria/odn: add new image sizes
- b8646357f6701d6e73118521cffff6f69835b59f: docs: add [Valkyria][151023]Seikishi Celsia ~Akuratsutaru Himegimi~

Example image:

![back0269](https://cloud.githubusercontent.com/assets/1045476/19245536/f6c604a0-8f21-11e6-9cab-e775d8762ac4.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.
