### ISSUE TITLE
Game request: [Tinkerbell][141219]Ouma no Shoku ~Sei ni Tsukaeshi Yami no Guuzou~

### ISSUE THREAD

**Issue by AlchemistofAtlas** [vn-tools/arc_unpacker#79]
VNDB link: https://vndb.org/v15845
Developer: TinkerBell
Release date: 2014-12-19
Original title: 逢魔ノ喰 ～聖に仕えし闇の偶像～
English title (if available): 

May you also support this title, please? Checked, and unlike Shukubo no Uzuki 2, doesn't have appendix files to be looked upon.

**Comment by rr-** [comment]
Done:

- 6935fe9a3b7204a349d13aec0bcfeb22514d44a2: dec/cyberworks/dat: add ouma-no-shoku plugin
- 4b07ce4e26f16a9f7a88c5db79b67bb29af230c6: docs: add [Tinkerbell][141219]Ouma no Shoku ~Sei ni Tsukaeshi Yami no Guuzou~

Example image:

![unk_2814](https://cloud.githubusercontent.com/assets/1045476/19290372/af369c3c-900f-11e6-9b05-7d47fd2846d9.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by AlchemistofAtlas** [comment]
Ok, worked without problems. Thank you. =D
