### ISSUE TITLE
Game request: [Erectlip][120224]Furyou ni Hamerarete Jusei Suru Kyonyuu Okaa-san ~Iki Jigoku ni Ochita Kazoku no Game~

### ISSUE THREAD

**Issue by pieman11** [vn-tools/arc_unpacker#80]
## Game info

VNDB link: https://vndb.org/v9643
Developer: Erectlip
Release date: 2012-02-24
Original title: 不良にハメられて受精する巨乳お母さん ～イキ地獄に堕ちた家族のゲーム～
English title (if available): 

## Details
Looks like several Erectlip games, including a few from around the same time-period as this one, are currently supported. Unfortunately, arc_unpacker can't seem to figure out this particular one's formatting.
 All of the data files are .pac.

**Comment by rr-** [comment]
Done:

- 0ad6f2d36411e5977151e41e4cbf09de77c1545b: dec/amuse-craft/pac: simplify variant 2 detection
- 21ed7f9f597b5edf0f28dc1a06c7c7f7864e43f8: docs: add [Erectlip][120224]Furyou ni Hamerarete Jusei Suru Kyonyuu Okaa-san ~Iki Jigoku ni Ochita Kazoku no Game~

Example image:

![stl000a](https://cloud.githubusercontent.com/assets/1045476/19316186/bc56a092-90a0-11e6-853a-da99217a585e.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by pieman11** [comment]
That turn around time is incredible! I'll make sure to try it out once tonight't build is released. I'm glad you're around, otherwise I would never be able to acquire the music used in the game. It's a shame these Visual Novel makers often don't officially release their soundtracks.

**Comment by pieman11** [comment]
Tried it and it worked flawlessly! It would've been a shame had the BGM been left to rot, forgotten. Keep up the amazing work!
