### ISSUE TITLE
Game request: [TinkerBell][160428]Inyouchuu Goku ~Ryoushoku Jigoku Taimaroku~

### ISSUE THREAD

**Issue by marconii2002** [vn-tools/arc_unpacker#81]
## Game info

VNDB link: https://vndb.org/v18918
Developer: TinkerBell
Release date: 28-04-2016
Original title: 淫妖蟲 獄～凌触地獄退魔録～ 
English title (if available): 

## Details
Can you add upport for this game ?

**Comment by rr-** [comment]
Done:

- 81eead8784ea89fedc047a0c7a4ff5ad4e96003d: dec/cyberworks/dat: add inyou-goku plugin
- db304863a00df7b9d055b187774af1ff79cf5621: dec/cyberworks/dat: add inyou-rei-1 plugin
- ff4c01dd86a4d8ad407a52b5ec9c44ddf1b056f4: dec/cyberworks/dat: add inyou-rei-2 plugin
- 57e1c7e46afad706aca342028263b0213cfa6439: docs: add [TinkerBell][160428]Inyouchuu Goku ~Ryoushoku Jigoku Taimaroku~
- 73b3597c1cecbda9967292421532f6a0c2bde7e0: docs: add [TinkerBell][160428]Inyouchuu Rei ~Ryoujoku Shiro Taima Emaki~

Example image:

**Inyouchuu Goku ~Ryoushoku Jigoku Taimaroku~**:

![goku](https://cloud.githubusercontent.com/assets/1045476/19326397/a39eae8a-90ca-11e6-87e9-4b5b6cba9af4.png)

**In'youchuu Rei ~Ryoujoku Shiro Taima Emaki~** (from the same release):

![unk_381](https://cloud.githubusercontent.com/assets/1045476/19326536/3cd19842-90cb-11e6-83dc-b1d59c1f56b3.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by marconii2002** [comment]
I saw that you also added support for In'youchuu Rei ~Ryoujoku Shiro Taima Emaki~ (Miyuki Hen) and In'youchuu Rei ~Ryoujoku Shiro Taima Emaki~ (Yui Hen) Can you send me this games I want rip them.

**Comment by rr-** [comment]
They're from the same release 160428
