### ISSUE TITLE
Game request: [Tabito][130131]Okami Tsuma ~Ryokan Baito de no Himitsu~

### ISSUE THREAD

**Issue by AlchemistofAtlas** [vn-tools/arc_unpacker#82]
## Game info

VNDB link: https://vndb.org/v9694
Developer: Tabito
Release date: 2013-01-31
Original title: 	女将妻～旅館バイトでの秘密～
English title (if available): 

May you support this game as well, please? I also have the theory it could be using the cyberworks dec since it uses arc and dat format.

Thanks beforahand

**Comment by rr-** [comment]
I can't find it anywhere at all...

**Comment by AlchemistofAtlas** [comment]
I have it, I can pass it to you if you want.

**Comment by rr-** [comment]
If that wouldn't be a problem :-3 (Please use e-mail rather than posting stuff here)

**Comment by AlchemistofAtlas** [comment]
Don't worry, it's not a problem at all. Sent to your mail. If there's any problems with the DL or the game, plesae, let me know.

**Comment by rr-** [comment]
I've examined the files and it's not `cyberworks/dat`; I'll work on this once I get back home.

**Comment by rr-** [comment]
Done:

- 8b2579a624537793829f9aa72af1220f8f6e5fd4: dec/tabito/dat: initial support
- ef37cbc85cd34712d6e2d3ee09f5c1fccc42fa0b: dec/tabito/gwd: initial support
- 6389151d20718dfa57fc4f3d2db572ea817fecda: docs: add [Tabito][130131]Okami Tsuma ~Ryokan Baito de no Himitsu~

Example image:

![h_rouka02](https://cloud.githubusercontent.com/assets/1045476/19410129/7be7862a-92e4-11e6-9936-fc1c60850fca.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by AlchemistofAtlas** [comment]
Well, the extraction was complete, but was the char sprite meant to have black bacground? Because that's how it came out on the extraction.

**Comment by rr-** [comment]
Yes

**Comment by rr-** [comment]
Actually no...

**Comment by rr-** [comment]
Fixed:

- b9b6da9c68fe4104562583967c2208979e292d1c: dec/tabito/gwd: support alpha masks

Example image:

![t_re0201](https://cloud.githubusercontent.com/assets/1045476/19418666/c426fce2-93c8-11e6-9196-402558d93715.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by AlchemistofAtlas** [comment]
Ok, now it worked without problems. Thank you.
