### ISSUE TITLE
Game request: [Black Lilith][160729]Ochiru Hitozuma ~Animation~

### ISSUE THREAD

**Issue by mslzjq** [vn-tools/arc_unpacker#83]
## Game info

VNDB link: https://vndb.org/v8606
Developer: [Black Lilith](https://vndb.org/p1413)
Release date: 2016-07-29
Original title: 堕ちる人妻～Animation～
English title (if available): 

## Details

It seems like the developers used "TVP(KIRIKIRI) Z core" engine so it's kinda new. They usually use "TVP(KIRIKIRI) 2 core" though.
Note: It's a new release. Don't mistake it for the earlier 2011-12-23 release.

**Comment by marconii2002** [comment]
@mslzjq Use xp3viewer

**Comment by mslzjq** [comment]
@marconii2002 I've been using xp3viewer for all of my Kirikiri games but this one won't work.

**Comment by AlchemistofAtlas** [comment]
@mslzjq Ochiru Hitozuma uses KrKrExtract instead.

**Comment by mslzjq** [comment]
@AlchemistofAtlas Ok thanks.

**Comment by rr-** [comment]
Done:

- 6950cac29e0ffb6e099aa250bdf511cce98b773c: dec/kirikiri/xp3: support eliF entries
- c666c3f74e59875f3e209e69b814f2c0e64d695c: docs: add [Black Lilith][160729]Ochiru Hitozuma ~Animation~

Example image:

![nc022b](https://cloud.githubusercontent.com/assets/1045476/19412087/539ddd20-930e-11e6-9316-4bbf8626aadf.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.
