### ISSUE TITLE
Game request: [Eroitto][150227]Kaa-san no Otoko ~Yajuu no You na Otoko ni Mesu no Yorokobi o Oboesaserareru Saiai no Haha~

### ISSUE THREAD

**Issue by mslzjq** [vn-tools/arc_unpacker#84]
## Game info

VNDB link: https://vndb.org/v16720
Developer: [Eroitto](https://vndb.org/p3450)
Release date: 2015-02-27
Original title: 母さんのオトコ ～野獣のような男に牝の悦びを覚えさせられる最愛の母～
English title (if available): 

## Details

I just tried to extract the archive and the console gave me this error:
[task 0] graphic~.dat: initial recognition...
[task 0] graphic~.dat: guessing decoder among 278 decoders...
[task 0] graphic~.dat: recognized as nscripter/nsa.
[task 0] graphic~.dat: recognition finished with errors:
[task 0] graphic~.dat: boost::filesystem::path codecvt to wstring: error
Executed 1 tasks in 895.27s (1 problem, 0 saved files)

Actually, I can already extract this with crass v0.4.14.0 but since this game is not in the supported list, might as well post it here.
Crass extract everything but the scenario text is not decoded. I don't know if anyone is interested in the scenario text but I'm one of those that's interested.
Can you decode the scenario text too?
Not many developers are as active as you in developing decoding tools nowadays. I hope this tool can support broader VN engine and more games.
The log said it used PJADV.cui. Hope this little information helps.

**Comment by rr-** [comment]
>Can you decode the scenario text too?

I'll see about that, I can do it if it's simple

**Comment by mslzjq** [comment]
Thanks for the offer. If it's too much of a hassle for you then it's okay.
I'm actually interested to see the scenario structure.
The dialogue would have a voice file name right next to it, so I used to parse the scenario text using regex so it's more readable.
I know it's weird but I used to read it raw like that, haha. To learn Japanese and to copy paste the kanji I don't understand.
But now I use [VNR](http://sakuradite.com/wiki/en/vnr) to play while learning Japanese.
I just want to know what audio file is saying what so if I don't understand I can copy the dialogue in the scenario text and google translate it.

**Comment by rr-** [comment]
The scenario is a compiled script containing machine code that is useless to humans, I won't be decoding that as per README. On the other hand, all of the in-game text is stored in a separate file, `dltextdata.dat`. It's encrypted, but `arc_unpacker` will decrypt it.

**Comment by rr-** [comment]
Done:

- a2b2b3e10b4a68c5e0b2c619fe1500e36bb9743b: dec/pajamas/gamedat: initial support
- ba825b15770b9ca87a6e128ac426a7ee38dac794: dec/pajamas/ep: initial support
- 79b1537c3f1bec4f3546b92eef7e0b0621966124: docs: add [Eroitto][150227]Kaa-san no Otoko ~Yajuu no You na Otoko ni Mesu no Yorokobi o Oboesaserareru Saiai no Haha~

Example image:

![mi_n_04](https://cloud.githubusercontent.com/assets/1045476/19412952/1f54be7c-9321-11e6-888a-2736e74e16e6.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by mslzjq** [comment]
@rr- Thanks a lot!
