### ISSUE TITLE
Game request: [Pajamas Soft][140420]Ren'ai Harem ~Daisuki tte Iwasete~

### ISSUE THREAD

**Issue by marconii2002** [vn-tools/arc_unpacker#85]
## Game info

VNDB link: https://vndb.org/v13841
Developer: Pajamas Soft
Release date: 20-04-2014
Original title: 恋愛はーれむ ～大好きって言わせて～
English title (if available): 

## Details

Can you add support for this game ?

**Comment by rr-** [comment]
Done:

- e69d083c135468aca8cff9ef79d040273da61826: dec/lucifen/lpk: add renai-harem plugin
- cbc81cc2aeeacf916afc2ea188b6c22433622419: docs: add [Pajamas Soft][140420]Ren'ai Harem ~Daisuki tte Iwasete~

Example image:

![ec05](https://cloud.githubusercontent.com/assets/1045476/19418219/ec16ed9c-93bf-11e6-9f3b-efc7fc6c6903.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.
