### ISSUE TITLE
Game request: [Minato Soft][150520]Yuuki Yuuna Is A Hero S

### ISSUE THREAD

**Issue by NepNep** [vn-tools/arc_unpacker#87]
## Game info

VNDB link: https://vndb.org/v16682
Developer: Minatosoft
Release date: 2015-05-20
Original title:     結城友奈は勇者であるS
## Details

I'd like to rip the sprites and sounds from the game if possible. When I drag the .exe to the unpacker, it only rips a few things and I can't seem to open them with anything. http://i1168.photobucket.com/albums/r483/SeeressYeul/Clipboard01.png

**Comment by marconii2002** [comment]
Can you show me game folder content ?
May be this game use LiveMaker engine.

**Comment by NepNep** [comment]
http://i1168.photobucket.com/albums/r483/SeeressYeul/junk/yuyuyu1.png
http://i1168.photobucket.com/albums/r483/SeeressYeul/junk/pluginfolder.png
The 結城友奈は勇者であるＳ~.exe folder contains the files ripped from the unpacker.

**Comment by marconii2002** [comment]
You should try rip arc0.dat arc1.dat arc2.dat not exe files.

**Comment by NepNep** [comment]
Alright. I'll try that!

**Comment by marconii2002** [comment]
Can you send me this dat files

**Comment by NepNep** [comment]
They're [here](https://mega.nz/#!9cswWLwb!uEUX3MsxKxT18h7r026vQNk42F-uRRV3XhqzyaZNxFY).

**Comment by marconii2002** [comment]
Game use Whale engine. Support must be added.

**Comment by rr-** [comment]
Can you upload it to 0x0.st or catbox.moe rather than mega? Thanks.

**Comment by NepNep** [comment]
I had to separate them into their own archives otherwise it was too big!
https://files.catbox.moe/z27zq0.rar
https://files.catbox.moe/2l1721.rar
these last three are arc2 because it was too big for either site by itself.
https://files.catbox.moe/ihgu1p.rar
https://files.catbox.moe/oburnl.rar
https://files.catbox.moe/pixc5p.rar

**Comment by rr-** [comment]
I'll also need the other files, including game .exe.

**Comment by NepNep** [comment]
The files are too big to upload them to the websites you mentioned before but you can get the VN from [here](http://pastebin.com/2wvjCyrV) if it's not a problem.

**Comment by rr-** [comment]
All I see there are more links to mega. I can't use mega because somehow their bandwidth limits never expire for me so I can't get anything in 100%.

**Comment by NepNep** [comment]
Will [mediafire](http://www.mediafire.com/file/b8fi484tc40iz12/YukiYunaS.rar) work?

**Comment by rr-** [comment]
Looks like so, thanks

**Comment by NepNep** [comment]
You're welcome!

**Comment by rr-** [comment]
Yay it's protected with Themida

**Comment by rr-** [comment]
To be able to decrypt files from this engine, you need to know the original file names. The archives used by the game do not provide the file names so I have to guess them.

I have guessed about 8000 file names, but I was unable to discover names of 111 files. As far as I'm concerned the game doesn't use those files...? Most of these unknown files are either miscellaneous CG (not characters, backgrounds nor event images) or sound effects.

I'll keep at it for a few more hours but if I'm unable to come up with anything more I'll call it a day and push the results as they are.

**Comment by rr-** [comment]
Done:

- e52cca484d5fe8797022d2dbd612d92cf4a0110b: etc: add file names for [Minato Soft][150520]Yuuki Yuuna Is A Hero S
- b21bcc1d8861fc6dacae58b4c0e159bdc1cf8d4e: docs: add [Minato Soft][150520]Yuuki Yuuna Is A Hero S

I managed to decode the remaining CGs (which turned out to be some creature cards and Major Arcana Tarot cards), but decided to give up on remaining files which are all miscellaneous sound effects in the number of ~60 - I don't think it's a huge loss.

Example image:

![ev_005_01_11](https://cloud.githubusercontent.com/assets/1045476/20449022/3e567b2c-ade7-11e6-8b0f-25617a985ccc.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.
