### ISSUE TITLE
Game request: [Campus][161028]Deep Love Diary -Koibito Nikki-

### ISSUE THREAD

**Issue by marconii2002** [vn-tools/arc_unpacker#90]
## Game info

VNDB link: https://vndb.org/r47131
Developer: Campus
Release date: 28-10-2016
Original title: Deep Love Diary -恋人日記- 通常版
English title (if available): 
## Details

Can you add support for this game ?

**Comment by rr-** [comment]
Done:

- 84cd14e1eb33f95c8fba8bde72f607e89dae77af: dec/malie/lib*: refactor; add new plugins
- 79c301c23ccc5e8e9cf11dd0276eaef0e69555b7: dec/google/webp: initial support
- fbd38efc45d6bbb798f7d84a8c6fc92b95192ac0: dec/malie/dzi: initial support
- 5d4457274952bc53bf96d58a5161613288286c81: docs: add [Campus][161028]Deep Love Diary -Koibito Nikki-

Example image:

![04a_0](https://cloud.githubusercontent.com/assets/1045476/20462278/d7a6230e-af18-11e6-8c62-de51a5314e55.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.

**Comment by marconii2002** [comment]
So how to rip this game ?

I downloaded and installed game but  I dont have any libp files. I have only one big data.dat file

**Comment by rr-** [comment]
That's the file you're supposed to use it on, along with `--dec` and `--plugin`.

Decoder names are often unrelated to the file names (think how .mkv containers contain h264 encoded data)

**Comment by Unamed-git** [comment]
help me. how i can find the libp archive key?
