### ISSUE TITLE
Game request: [Youkai Tamanokoshi (CHIRO)][111231]Tsumadori

### ISSUE THREAD

**Issue by marconii2002** [vn-tools/arc_unpacker#91]
## Game info

VNDB link: https://vndb.org/v13390
Developer: Youkai Tama no Koshi
Release date: 31-12-2011
Original title: つまどり
English title (if available): 
## Details

Can you add support for this game ?
All my CG extraction tools failed on this game. Only ExtractData opened sound.dat and voice.dat but not grp.dat

**Comment by rr-** [comment]
Done:

- 85b99ac75eecc7e627c812d275a12486cc704ba4: dec/chanchan/dat: initial support
- 531299640792b218b195e59d341a472e2934073b: docs: add [Youkai Tamanokoshi][111231]Tsumadori

Example image:

![default](https://cloud.githubusercontent.com/assets/1045476/20464757/d59784b0-af4d-11e6-8f00-38f7214f387a.jpg)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

If you experience any problems, feel free to reopen the issue.
