### ISSUE TITLE
.bk2: not recognized by any decoder.

### ISSUE THREAD

**Issue by Chipp12** [vn-tools/arc_unpacker#92]
Sorry if this sounds like a noob question but for some reason I can't unpack cc_ed001a.bk2 and cc_ed002a.bk2 files (ending movies from Chaos;Child) using --dec=mages/mpk option even though that format is listed in the gamelist.

**Comment by rr-** [comment]
Those are movies encoded in proprietary format, I don't think I intend to decode them cause so far the interest in movies was very low

**Comment by Chipp12** [comment]
Oh, so that's how it is. I just wanted to compare console and PC staff quickly without getting/installing the whole game but I guess I'll have to ho 100% save way then. Thanks for the answer!

**Comment by rr-** [comment]
(Note that the event pictures and sound are inside `.mpk` archives)
