### ISSUE TITLE
Game request: [Purple Software][160729] Amatsutsumi

### ISSUE THREAD

**Issue by PeratX** [vn-tools/arc_unpacker#97]
## Game info

VNDB link: https://vndb.org/r44574
Developer: Purple Software
Release date: 2016-07-29
Original title: アマツツミ
English title (if available): Amatsutsumi

## Details

Can you add support for decoding ps2(ps3) scripts?

**Comment by PeratX** [comment]
https://github.com/SherrinaFanClub/Amatsutsumi
This may be help.

**Comment by PeratX** [comment]
https://github.com/nsmr0604/cpz3unpack
Old CPZ files process.

**Comment by 0xh3LL0** [comment]
if you ask the author about extracting CG, sound, etc... he'll do it (probably)
but afaik, not with script (which used for translation)

if you want to deal with purple software script, use this instead...
https://github.com/xmoeproject/X-moe/tree/master/Unpacker/PurpleSoftware
tested by me and works on both amatsutsumi and hapy maher

**Comment by PeratX** [comment]
@0xh3LL0 Thanks.

**Comment by sharin-sub** [comment]
@0xh3LL0 @PeratX 
Did you have the tools?
Looks like the repository was closed. Could you please send me the tools if you have them?
